name: app
description: "Colmeia Smart — Sistema de Monitorização de Colmeias"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # HTTP
  dio: ^5.7.0

  # Secure token storage
  flutter_secure_storage: ^9.2.2

  # Local offline DB (for BLE data queue)
  hive_flutter: ^1.1.0

  # Charts
  fl_chart: ^0.66.2

  # BLE
  flutter_blue_plus: ^1.34.5

  # Network status
  connectivity_plus: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
