[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_src_filter = +<*> -<calibrate/>

lib_deps =
    adafruit/RTClib @ ^2.1.4
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    h2zero/NimBLE-Arduino @ ^1.4.3
    https://github.com/olkal/HX711_ADC.git

[env:calibrate]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
build_src_filter = -<*> +<calibrate/>

lib_deps =
    https://github.com/olkal/HX711_ADC.git